### ISSUE TITLE
Servercrash on fresh install

### ISSUE THREAD

**Issue by supermopf** [dalexhd/SteamSpeak#152]
## 🐛 Bug Report

The Server crashes, after a fresh install. 

## To Reproduce

1. Download Release 0.8.1
2. Follow the installation guide
3. Run `yarn run start:server`

## Expected behavior

The Server starts and the website is reachable.

## Actual Behavior

The Server crashes and the website is not reachable.

```
[02-07-2020 14:30:02.450] [Cache] Connected to redis.
[02-07-2020 14:30:02.473] [Database] Connected to the database!
[02-07-2020 14:30:03.134] [Steam] logged in.
[02-07-2020 14:30:03.524] [Steam] Counter-Strike: Global Offensive disabled. Skipping
[02-07-2020 14:30:03.570] [Steam] Loaded module friendRequest.
[02-07-2020 14:30:03.753] [Steam] Loaded module richPresence.

/home/steamspeak/SteamSpeak/node_modules/binarykvparser/index.js:23
        if (buffer.toBuffer) {
            ^
TypeError: Cannot read property 'toBuffer' of null
    at Object.exports.parse (/home/steamspeak/SteamSpeak/node_modules/binarykvparser/index.js:23:13)
    at /home/steamspeak/SteamSpeak/packages/server/node_modules/steam-user/components/apps.js:249:37
    at Array.forEach (<anonymous>)
    at SteamUser.<anonymous> (/home/steamspeak/SteamSpeak/packages/server/node_modules/steam-user/components/apps.js:245:27)
    at SteamUser._handleMessage (/home/steamspeak/SteamSpeak/packages/server/node_modules/steam-user/components/messages.js:543:34)
    at SteamUser._handleNetMessage (/home/steamspeak/SteamSpeak/packages/server/node_modules/steam-user/components/messages.js:480:7)
    at SteamUser.processMulti (/home/steamspeak/SteamSpeak/packages/server/node_modules/steam-user/components/messages.js:572:9)
    at Gunzip.cb (/home/steamspeak/SteamSpeak/packages/server/node_modules/steam-user/components/messages.js:563:17)
    at Gunzip.zlibBufferOnEnd (zlib.js:151:10)
    at Gunzip.emit (events.js:315:20)
    at Gunzip.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
steamspeak@gamerangerz:~/SteamSpeak$ [02-07-2020 14:30:05.963] [First Instance][Ts3] Subscribed to all Events.
[02-07-2020 14:30:05.971] [First Instance][Ts3] Host message disabled. Skipping
[02-07-2020 14:30:05.972] [First Instance][Ts3] Multi function disabled. Skipping
[02-07-2020 14:30:06.102] [Second Instance][Ts3] Subscribed to all Events.
[02-07-2020 14:30:06.121] [Second Instance][Ts3] AFK kick disabled. Skipping
[02-07-2020 14:30:06.121] [Second Instance][Ts3] AFK move disabled. Skipping
[02-07-2020 14:30:06.122] [Second Instance][Ts3] Change channel disabled. Skipping
[02-07-2020 14:30:06.122] [Second Instance][Ts3] Server Name disabled. Skipping
[02-07-2020 14:30:06.126] [Second Instance][Cache] Connected to redis.

````

## Your Environment
- SteamSpeak version used: 0.8.1
- Environment name and version: Node.js v14.4.0
- Operating system and version: Ubuntu 18.04.4 LTS
- Steam Config: Account using 2FA

**Comment by dalexhd** [comment]
Hi @supermopf 😄 

I'll need a bit more info to know that is causing this issue.

What I know:
1. The function causing this exception is getProductInfo(), here is the full function: https://github.com/DoctorMcKay/node-steam-user/blob/cc39197c4bd554b505dadff5b464c80f5b4d67df/components/apps.js#L230
1. That means that the problem is the Dynamic Banner Generation: https://github.com/dalexhd/SteamSpeak/blob/98471205a3ba1f271a9f36fdc7796170501cddb5/packages/server/src/core/Steam/modules/richPresence.ts#L162

To go in deeper I will need you to:
1. Checkout the dev branch (This branch contains some fixes and also better logging system)
1. Enable Steam debug at your config file: https://github.com/dalexhd/SteamSpeak/blob/98471205a3ba1f271a9f36fdc7796170501cddb5/packages/server/src/config/steam.sample.ts#L7
1. Run `yarn install`
1. Run the bot and change the game you're playing at Steam. (You should already be verified with your Steam Bot)
1. Post the content of your log file generated at `packages/server/logs` directory (Obfuscate any credentials before posting).
1. Post your Linux screen output like you did before.

**Comment by supermopf** [comment]
Hey @dalexhd,

i followed your steps, but there was no file in `packages/server/logs`

The crash happens on start, so changing the game is not relevant i guess.

Anyway, heres the terminal output:

```
yarn run v1.22.4
$ yarn --cwd ./packages/server start
$ cd ../../ && make check-config
$ cross-env TS_NODE_FILES=true NODE_ENV=production ts-node -r tsconfig-paths/register src/index.ts

/home/steamspeak/SteamSpeak/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/core/Website/api/controllers/verify.ts:116:26 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ uid: string; dbid: string; steamId: any; }' is not assignable to parameter of type 'Pick<{ _id: any; uid: string; dbid: string; steamId: string; groupId: any; groupNumber: any; } & { _id: any; }, "uid" | "dbid" | "steamId" | "groupId" | "groupNumber"> & { _id?: any; }'.
      Type '{ uid: string; dbid: string; steamId: any; }' is missing the following properties from type 'Pick<{ _id: any; uid: string; dbid: string; steamId: string; groupId: any; groupNumber: any; } & { _id: any; }, "uid" | "dbid" | "steamId" | "groupId" | "groupNumber">': groupId, groupNumber

116             VerifiedClient.create({
                                      ~
117                     uid: client.uniqueIdentifier,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
119                     steamId: steamData.steamId
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
120             });
    ~~~~

  ../../node_modules/@types/mongoose/index.d.ts:3273:5
    3273     create<TCreate = T>(...docs: CreateQuery<TCreate>[]): Promise<T>;
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.

    at createTSError (/home/steamspeak/SteamSpeak/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/home/steamspeak/SteamSpeak/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/home/steamspeak/SteamSpeak/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/home/steamspeak/SteamSpeak/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/home/steamspeak/SteamSpeak/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.require.extensions.<computed> [as .ts] (/home/steamspeak/SteamSpeak/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/steamspeak/SteamSpeak/packages/server/src/core/Website/api/routes/verify.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module.m._compile (/home/steamspeak/SteamSpeak/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.require.extensions.<computed> [as .ts] (/home/steamspeak/SteamSpeak/node_modules/ts-node/src/index.ts:861:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dalexhd** [comment]
Sorry about that compilation error. It was a mongoose typescript mistake Fixed at #154 

Can you try the same steps I told you at  https://github.com/dalexhd/SteamSpeak/issues/152#issuecomment-653045128

**Comment by supermopf** [comment]
Hey,

on dev branch this issue does not exist. So i think you can close this with the next release.

Thanks for the quick support^^

**Comment by dalexhd** [comment]
That are good news 😄.
